CREATE TABLE IF NOT EXISTS `users` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `email` varchar(60) NOT NULL,
  `password` varchar(40) NOT NULL,
  `status` varchar(5) NOT NULL DEFAULT 'no',
  `usertype` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `users` (`id`, `name`, `email`, `password`, `status`, `usertype`) VALUES
(1, 'aaa', 'aaa@gmail.com', 'd9f6e636e369552839e7bb8057aeb8da', 'yes', 'Doctor'),
(2, 'Nirthika', 'nirthika.rajendran@gmail.com', '2ee5e53b736fc1b9e340cd96bad4780e', 'no', 'Doctor'),
(3, 'bbb', 'bbb@gmail.com', '003d81296cbed643579b24d1cf6c907c', 'yes', 'MOH'),
(4, 'ccc', 'ccc@gmail.com', '57a8bdf56042b790fee5c0d54f33a746', 'no', 'MOH'),
(5, 'ddd', 'ddd@gmail.com', '2523687e80f9e29ce70fbf25f546b31b', 'yes', 'PHI'),
(7, 'eee', 'eee@gmail.com', '2449759e91d4d6f5bc9b58f39aecf2a1', 'no', 'PHI'),
(8, 'fff', 'fff@gmail.com', 'b8052bb170d1b0e03402d356b8844cba', 'yes', 'RDHS'),
(9, 'ggg', 'ggg@gmail.com', '91901b18f5bd120309664b97d9792b71', 'no', 'RDHS'),
(10, 'hhh', 'hhh@gmail.com', 'bd63e3e1e52833ca0450d44a0890dc46', 'yes', 'EU'),
(11, 'iii', 'iii@gmail.com', 'df831a1b297e41b68d855a17eee0626b', 'no', 'EU');

CREATE TABLE IF NOT EXISTS `institute` (
  `insName` varchar(35) NOT NULL,
  `insType` text NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `gsDiv` text NOT NULL,
  `mohArea` text NOT NULL,
  PRIMARY KEY (`insName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `institute` (`insName`, `insType`, `addLine1`, `addLine2`, `province`, `district`, `gsDiv`, `mohArea`) VALUES
('Jaffna Teaching Hospital', 'Gov', 'aaaaa', 'qqqqqq', 'rrrrr', 'dddddd', 'sed234', 'ghjiuu');

CREATE TABLE IF NOT EXISTS `doctor` (
  `userId` int(8) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `regNo` varchar(8) NOT NULL,
  `designation` text NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `contactNoOffice` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `hospPermanent` text NOT NULL,
  `hospital2` text,
  `hospital3` text,
  `hospital4` text,
  `hospital5` text,
  `otherHospital` text,
  PRIMARY KEY (`regNo`),
  CONSTRAINT doctor_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `doctor` (`userId`, `firstName`, `lastName`, `regNo`, `designation`, `addLine1`, `addLine2`, `province`, `district`, `contactNoOffice`, `contactNoMobile`, `hospPermanent`, `hospital2`, `hospital3`, `hospital4`, `hospital5`, `otherHospital`) VALUES
(1, 'AAA', 'aaa', '123', 'Option 1', 'ad1', '', 'Option 2', 'Option 2', '0212219118', '077 111 1111', 'Sampanthar Modern Clinic', 'Royal Medical Centre', '', 'Pillaiyar Medi Clinic', '', '');

CREATE TABLE IF NOT EXISTS `eu` (
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,  
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `euDiv` varchar(8) NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `contactNoOffice` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `institute` text NOT NULL,
  PRIMARY KEY (`euDiv`),
  CONSTRAINT eu_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT eu_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `eu` (`userId`, `insName`, `firstName`, `lastName`, `euDiv`, `addLine1`, `addLine2`, `province`, `district`, `contactNoOffice`, `contactNoMobile`) VALUES
(10, 'Jaffna Teaching Hospital', 'HHH', 'hhh', 'hb84', 'ggggggggg', 'jjjjjjjj', 'kkkkk', 'ssssssss', '7272727272', '6969696969');

CREATE TABLE IF NOT EXISTS `moh` (
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `mohRegNo` varchar(8) NOT NULL,
  `mohArea` text NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `contactNoOffice` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `institute` text NOT NULL,
  PRIMARY KEY (`mohRegNo`),
  CONSTRAINT moh_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT moh_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `moh` (`userId`, `insName`, `firstName`, `lastName`, `mohRegNo`, `mohArea`, `addLine1`, `addLine2`, `province`, `district`, `contactNoOffice`, `contactNoMobile`) VALUES
(3, 'Jaffna Teaching Hospital', 'BBB', 'bbb', 'bhg57', 'vchgv', 'wwwwwww', 'uuuuuuuu', 'kkkkk', 'mmmmmm', '0999999999', '0212342346');

CREATE TABLE IF NOT EXISTS `phi` (
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `phiRegNo` varchar(8) NOT NULL,
  `phiRange` text NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `contactNoOffice` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `institute` text NOT NULL,
  PRIMARY KEY (`phiRegNo`),
  CONSTRAINT phi_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT phi_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `phi` (`userId`, `insName`, `firstName`, `lastName`, `phiRegNo`, `phiRange`, `addLine1`, `addLine2`, `province`, `district`, `contactNoOffice`, `contactNoMobile`) VALUES
(5, 'Jaffna Teaching Hospital', 'DDD', 'ddd', 'mkj23', 'hbjhui', 'ooooo', NULL, 'qqqqq', 'zzzzzzzz', '7868473645', '2424242424');

CREATE TABLE IF NOT EXISTS `rdhs` (
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `rdhsDiv` varchar(8) NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `contactNoOffice` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `institute` text NOT NULL,
  PRIMARY KEY (`rdhsDiv`),
  CONSTRAINT rdhs_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT rdhs_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `rdhs` (`userId`, `insName`, `firstName`, `lastName`, `rdhsDiv`, `addLine1`, `addLine2`, `province`, `district`, `contactNoOffice`, `contactNoMobile`) VALUES
(8, 'Jaffna Teaching Hospital', 'FFF', 'fff', 'jhbu56', 'yyyyyyyyyyy', NULL, 'rrrrrrrrr', 'bbbbbbbb', '4848484848', '2524242424');

CREATE TABLE IF NOT EXISTS `patient` (
  `paId` varchar(8) NOT NULL,
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `nickName` text,
  `gender` text NOT NULL,
  `birthDate` date NOT NULL,
  `age` int(3) NOT NULL,
  `nextOfKin` text,
  `guardian` text,
  `guardianName` text,
  `ethnicGroup` text,
  `resAddLine1` text NOT NULL,
  `resAddLine2` text,
  `resProvince` text NOT NULL,
  `resDistrict` text NOT NULL,
  `resDsDiv` text NOT NULL,
  `resGsDiv` text NOT NULL,
  `redMohArea` text NOT NULL,
  `resPhiRange` text NOT NULL,
  `redLandmark` text NOT NULL,
  `curAddLine1` text NOT NULL,
  `curAddLine2` text,
  `curProvince` text NOT NULL,
  `curDistrict` text NOT NULL,
  `curDsDiv` text NOT NULL,
  `curGsDiv` text NOT NULL,
  `curMohArea` text NOT NULL,
  `curPhiRange` text NOT NULL,
  `curLandmark` text NOT NULL,
  `contactNoMobile` text NOT NULL,
  `contactNoHome` text NOT NULL,
  PRIMARY KEY (`paId`),
  CONSTRAINT pa_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT pa_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `notification` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userId` int(8) NOT NULL,
  `insName` varchar(35) NOT NULL,
  `paId` varchar(8) NOT NULL,
  `diseaseGroup` text NOT NULL,
  `diseaseName` text NOT NULL,
  `onsetDate` date NOT NULL,
  `regDate` date NOT NULL,
  `regOrBHTNo` text NOT NULL,
  `ward` text NOT NULL,
  `labResult` text,
  PRIMARY KEY (`id`),
  CONSTRAINT noti_user_id FOREIGN KEY (userId) REFERENCES users(id) ON UPDATE CASCADE,
  CONSTRAINT noti_ins_name FOREIGN KEY (insName) REFERENCES institute(insName) ON UPDATE CASCADE,
  CONSTRAINT noti_pa_id FOREIGN KEY (paId) REFERENCES patient(paId) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `h411a` (
  `notifyId` varchar(8) NOT NULL,
  `rdhsDiv` varchar(8) NOT NULL,
  `mohArea` text NOT NULL,
  `mohRegNo` varchar(8) NOT NULL,
  `birthDate` date NOT NULL,
  `age` int(3) NOT NULL,
  `gender` text NOT NULL,
  `occupation` text NOT NULL,
  `sourceOfNotify` text NOT NULL,
  `diseaseAsNotify` text NOT NULL,
  `dateOfNotify` date NOT NULL,
  `diseaseAsConf` text NOT NULL,
  `dateOfConf` date NOT NULL,
  `confirmedBy` text NOT NULL,
  `natureOfConf` text NOT NULL,
  `officeNote` text NOT NULL,
  PRIMARY KEY (`notifyId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `h399` (
  `entryId` varchar(8) NOT NULL,
  `weekEndDate` date NOT NULL,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `rdhsDiv` varchar(8) NOT NULL,
  `mohArea` text NOT NULL,
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `weeklySummary` (
  `entryId` varchar(8) NOT NULL,
  `summary` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `chankanai` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `chavakachcheri` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `jaffna` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `karaveddy` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `kayta` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `kopay` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `nallur` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `pointpedro` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `sandilipay` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `tellipalai` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `uduvil` (
  `entryId` varchar(8) NOT NULL,
  `phiArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `total` (
  `entryId` varchar(8) NOT NULL,
  `mohArea` text NOT NULL,
  `cholera` int(5),
  `polio` int(5),
  `chickenPox` int(5),
  `dengue` int(5),
  `diphtheria` int(5),
  `dysentery` int(5),
  `encephalitis` int(5),
  `entericFever` int(5),
  `foodPoisoning` int(5),
  `humanRabies` int(5),
  `leptospirosis` int(5),
  `malaria` int(5),
  `neasles` int(5),
  `meningities` int(5),
  `mumps` int(5),
  `rubella` int(5),
  `congenitalRubella` int(5),
  `sampleConFever` int(5),
  `tetanus` int(5),
  `neonatal` int(5),
  `typhusFever` int(5),
  `viralHepatitis` int(5),
  `whoopingCough` int(5),
  `tuberculosis` int(5),
  PRIMARY KEY (`entryId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `h411` (
  `notifyId` varchar(8) NOT NULL,
  `phiRegNo` varchar(8) NOT NULL,
  `phiRange` text NOT NULL,
  `mohNotifyNo` text NOT NULL,
  `mohArea` text NOT NULL,
  `mohRegNo` varchar(8) NOT NULL,
  `diseaseNotified` text NOT NULL,
  `notifyDate` date NOT NULL,
  `diseaseConf` text NOT NULL,
  `confDate` date NOT NULL,
  `patFname` text NOT NULL,
  `patLname` text NOT NULL,
  `addLine1` text NOT NULL,
  `addLine2` text,
  `province` text NOT NULL,
  `district` text NOT NULL,
  `dsDiv` text NOT NULL,
  `gsDiv` text NOT NULL,
  `birthDate` date NOT NULL,
  `age` int(3) NOT NULL,
  `gender` text NOT NULL,
  `ethnicGroup` text,
  `onsetDate` date NOT NULL,
  `hospDate` date NOT NULL,
  `dischDate` date NOT NULL,
  `hospital` text NOT NULL,
  `outcome` text NOT NULL,
  `isolated` text NOT NULL,
  `patMovement` text NOT NULL,
  `labFinding` text NOT NULL,
  PRIMARY KEY (`notifyId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `contactInvesticate` (
  `notifyId` varchar(8) NOT NULL,
  `contId` varchar(8) NOT NULL,
  `firstName` text NOT NULL,
  `lastName` text NOT NULL,
  `age` int(3) NOT NULL,
  `seenDate` date NOT NULL,
  `opsevation` text NOT NULL,
  PRIMARY KEY (`notifyId`,`contId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `patientEventHistory` (
  `notifyId` varchar(8) NOT NULL,
  `symptomDevelop` text,
  `indigenous` text,
  `western` text,
  `bothTreatment` text,
  `noTreatment` text,
  `complication` text,
  `foreign` text,
  PRIMARY KEY (`notifyId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;